pipeline {

                agent any

                stages {

                                stage('Source') {

                                                steps {

                                                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], gitTool: 'default', submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/VijayaLakshmi2/ClaiMaster.git']]])

                                                }

                                }

                                stage('Build') {

                                                tools {

                                                                jdk 'jdk8'

                                                                maven 'apache-maven-3.5.4'

                                                }

                                                steps {

                                                                powershell 'mvn clean package'

                                                               

                                                }

                                }

                               

                                stage('Code Quality') {

                   steps {

                                                                                script{

                                                                                                withSonarQubeEnv(installationName: 'sonarqube1'){

                                                                                                bat label: '', script: 'mvn sonar:sonar'

                         }

                       }

                                   }

                               

                                }

                                }

                                }
